# Set var "WDIR" to workdir
<% if @args[0] %>
<% WDIR=@args[0] %> 
<% else %>
<% WDIR=ENV["PWD"] %>
<% end %>

name: <%= WDIR.split('/').last  %>
root: <%= @args[0] %>

startup_window: Test-1
windows:
  - Test-1:
      layout: tiled
      panes:
        - 
        - 
        - 
        - 
#  - listener:
#      layout: even-horizontal
#      panes:
#        - print -S 'ros2 run demo_nodes_cpp listener'
